### ISSUE TITLE
Create a TS block

### ISSUE THREAD

**Issue by Hartorn** [thc-tools/webpack-react#17]
## Feature request
Create a TS block

**What is the expected behavior?**
to have a block similar as for babel, but for typescript

**What is motivation or use case for adding/changing the behavior?**
Needed

**How should this be implemented in your opinion?**
Using classic ts-loader, and so on

**Are you willing to work on this yourself?**
yes

**Comment by Hartorn** [comment]
@c3dr0x Any idea / specials needs ? like using awesome type script loader? I would prefer going ts-loader, with some cache and so on.

**Comment by c3dr0x** [comment]
Nop i'm fine with ts-loader. As for some specifics nothing more that what we did for focus for now. :)
